name: Update DEPENDENCIES

on: 
  push:
    branches:
      - main
      - release/*
    paths-ignore:
      - DEPENDENCIES

jobs:
  dependencies:
    uses: pstuecker/build/.github/workflows/update-dependencies.yml@self-main
    permissions:
      contents: write
      issues: write
      pull-requests: write
    secrets:
      GH_BOT_TOKEN: test
